name: Documentation website

on: push


jobs:

  docs-site:
    name: Deploy documentation website
    # runs only for tagged commits
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    environment: Kubernetes
    needs: [test, code_quality]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # commented out until credentials are added
      # see https://github.com/Naseus/recipeCompete/issues/6
      #
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: jdevries3133
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Setup kube config
      #   run: mkdir ~/.kube && echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
      # - name: Deploy documentation site
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #   run: make deploy
